#!/bin/sh

imgdir=/mnt/sd.1/extlinux
#global.bootm.oftree=/mnt/sd.1/extlinux/dtb_5.16
#global.bootm.image=/mnt/sd.1/extlinux/Image_5.16.gz
#global.bootm.initrd=/mnt/sd.1/rootfs.cpio.lz4

global.bootm.oftree=$imgdir/dtb_5.16
global.bootm.image=$imgdir/Image_5.16.gz
global.bootm.initrd=/mnt/sd.1/rootfs.cpio.lz4

cd $imgdir
ls Image*
readline "which kernel? " imagefile
ls *dtb*
readline "which dtb? " dtbfile

if [ -n "$imagefile" ]; then
	global.bootm.image=$imgdir/$imagefile
fi
if [ -n "$dtbfile" ]; then
	global.bootm.oftree=$imgdir/$dtbfile
fi
#bootm
