#!/bin/sh

imgdir=/mnt/sd.1/extlinux
#global.bootm.image=/mnt/mmc1/zImage
#global.bootm.oftree=/env/oftree
#global.bootm.oftree=/mnt/sd.1/extlinux/dtb_5.16
#global.bootm.image=/mnt/sd.1/extlinux/Image_5.16.gz
#global.bootm.initrd=/mnt/sd.1/rootfs.cpio.lz4

global.bootm.oftree=$imgdir/dtb_5.16
global.bootm.image=$imgdir/Image_5.16.gz
global.bootm.initrd=/mnt/sd.1/rootfs.cpio.lz4

ls $imgdir
readline "which kernel? " imagefile
readline "which dtb? " dtbfile

if [ -n "$imagefile" ]; then
	global.bootm.image=$imgdir/$imagefile
fi
if [ -n "$dtbfile" ]; then
	global.bootm.oftree=$imgdir/$dtbfile
fi
bootm
